# specify MOODLE_BASE_URL and MOODLE_TOKEN in there
set dotenv-load := true

help *ARGS:
	@uv run mdl {{ARGS}} --help

show-course:
	uv run mdl courses
	uv run mdl contents 2
	uv run mdl module 2

upload *ARGS:
	@uv run mdl upload {{ARGS}}
