[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "moodlepy>=0.24.1",
    "requests>=2.32.3",
    "typst>=0.13.3",
]
